### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by anonrig** [patrickjquinn/P-Brain.ai#5]
Awful Javascript error is awful.

```javascript
{ responseType: 'fact',
  originalQuery: 'heavy rain move youtube' }
TypeError: Cannot read property 'length' of undefined
    at get_wlfra_result (/Users/anonrig/Documents/forks/P-Brain.ai/skills/fact/index.js:36:27)
    at next (native)
    at onFulfilled (/Users/anonrig/Documents/forks/P-Brain.ai/node_modules/co/index.js:65:19)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by patrickjquinn** [comment]
Basic fix was basic. Marking #closed
