### ISSUE TITLE
Replies with the same sentence I spoke

### ISSUE THREAD

**Issue by hemalchevli** [patrickjquinn/P-Brain.ai#7]
I'm on windows 7, I installed node js and yarn and started the project. The server is up but when I say a sentence, brain replies with the same sentence. Here is the error I got. Is there a way I can share more debug information. I'm noob with js. 
Awesome project by the way, cheers!

D:\gitlab\P-Brain.ai-master>yarn start
yarn start v0.19.1
$ node server.js
P-Brain is listening on port 4567
{ Error: ENOENT: no such file or directory, scandir 'D:\gitlab\P-Brain.ai-master\api\skills'
    at Error (native)
    at Object.fs.readdirSync (fs.js:951:18)
    at getDirectories (D:\gitlab\P-Brain.ai-master\api\core-ask.js:15:13)
    at train_recognizer (D:\gitlab\P-Brain.ai-master\api\core-ask.js:26:14)
    at next (native)
    at onFulfilled (D:\gitlab\P-Brain.ai-master\node_modules\co\index.js:65:19)
    at D:\gitlab\P-Brain.ai-master\node_modules\co\index.js:54:5
    at co (D:\gitlab\P-Brain.ai-master\node_modules\co\index.js:50:10)
    at toPromise (D:\gitlab\P-Brain.ai-master\node_modules\co\index.js:118:63)
    at next (D:\gitlab\P-Brain.ai-master\node_modules\co\index.js:99:29)
  errno: -4058,
  code: 'ENOENT',
  syscall: 'scandir',
  path: 'D:\\gitlab\\P-Brain.ai-master\\api\\skills' }
(node:4892) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: ENOENT: no such file or directory, scandir 'D:\gitlab\P-Brai
n.ai-master\api\skills'
192.168.0.72
TypeError: Cannot read property 'value' of undefined
    at Object._query [as query] (D:\gitlab\P-Brain.ai-master\api\core-ask.js:48:26)
    at next (native)
    at onFulfilled (D:\gitlab\P-Brain.ai-master\node_modules\co\index.js:65:19)
    at D:\gitlab\P-Brain.ai-master\node_modules\co\index.js:54:5
    at co (D:\gitlab\P-Brain.ai-master\node_modules\co\index.js:50:10)
    at toPromise (D:\gitlab\P-Brain.ai-master\node_modules\co\index.js:118:63)
    at next (D:\gitlab\P-Brain.ai-master\node_modules\co\index.js:99:29)
    at onFulfilled (D:\gitlab\P-Brain.ai-master\node_modules\co\index.js:69:7)
    at D:\gitlab\P-Brain.ai-master\node_modules\co\index.js:54:5
    at co (D:\gitlab\P-Brain.ai-master\node_modules\co\index.js:50:10)
TypeError: Cannot read property 'value' of undefined
    at Object._query [as query] (D:\gitlab\P-Brain.ai-master\api\core-ask.js:48:26)
    at next (native)
    at onFulfilled (D:\gitlab\P-Brain.ai-master\node_modules\co\index.js:65:19)
    at D:\gitlab\P-Brain.ai-master\node_modules\co\index.js:54:5
    at co (D:\gitlab\P-Brain.ai-master\node_modules\co\index.js:50:10)
    at toPromise (D:\gitlab\P-Brain.ai-master\node_modules\co\index.js:118:63)
    at next (D:\gitlab\P-Brain.ai-master\node_modules\co\index.js:99:29)
    at onFulfilled (D:\gitlab\P-Brain.ai-master\node_modules\co\index.js:69:7)
    at D:\gitlab\P-Brain.ai-master\node_modules\co\index.js:54:5
    at co (D:\gitlab\P-Brain.ai-master\node_modules\co\index.js:50:10)

![pbrain](https://cloud.githubusercontent.com/assets/948576/22372027/af2b11f4-e4c0-11e6-91cd-1f81bc08d68a.png)

**Comment by patrickjquinn** [comment]
This is happening because of how paths are handled on Windows if you go to "api/core-ask.js" and look at line 32 where it has "var intent_funct = require('../skills/'+dir).intent;", Windows doesnt appear the handle the "../" (which is directing it to the level above that directory) very well.

For the moment you might want to change all manually specified relative paths (like the one above) with absolute paths (i.e D:\gitlab\P-Brain.ai-master\<folder_name>\<file_name>.js).

I'll add in a "path.resolve" based system later to resolve this and test on Windows (I havent really been testing against Windows :( )

**Comment by patrickjquinn** [comment]
Thanks for the extremely detailed issue ticket by the way! I appreciate it, it makes the issue much easier to track down 👍

**Comment by hemalchevli** [comment]
Thanks for the quick reply. I understand you might not be testing on windows soon, that's cool, I'll try it out on Pi, tomorrow. I just saw project on hackaday and rushed to try it out. Ran in to this issue, thought might be useful. I'll update on this issue once I make any progress on it.
I'm actually trying to integrate jasper with home assistant. I'll give P-brain a go and see if there is any possibility of integrating with home assistant. I really like how the skills are modular and can be added. 
Thanks again :)
Cheers!

**Comment by patrickjquinn** [comment]
If you have a USB microphone then I would strongly suggest testing it out with the RasPi client https://github.com/patrickjquinn/P-Brain.ai-RasPi and in the mean time i'll look into the Windows issue and get back to you!

**Comment by staberas** [comment]
I solved it by moving the skill file into the \api file and fixing the following line
` var intent_funct = require('./skills/'+dir).intent;`
(and restarted it obviously)

**Comment by patrickjquinn** [comment]
Glad it worked okay for you, I'll find a more perminamt solution so you don't have to do this in future!
