### ISSUE TITLE
Install error node version incompatible

### ISSUE THREAD

**Issue by likegeo** [patrickjquinn/P-Brain.ai#70]
Get errors after yarn & yarn start:

c:\HomeAssistant>yarn start
yarn run v1.15.2
warning package.json: License should be a valid SPDX license expression
$ node server.js
Using default SQLite database provider
Setting up database.
Error: Cannot find module 'c:\HomeAssistant\node_modules\sqlite3\lib\binding\node-v72-win32-x64\node_sqlite3.node'
Require stack:
- c:\HomeAssistant\node_modules\sqlite3\lib\sqlite3.js
- c:\HomeAssistant\db\sqlite_db\index.js
- c:\HomeAssistant\db\index.js
- c:\HomeAssistant\server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:610:15)
    at Function.Module._load (internal/modules/cjs/loader.js:526:27)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (c:\HomeAssistant\node_modules\sqlite3\lib\sqlite3.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'c:\\HomeAssistant\\node_modules\\sqlite3\\lib\\sqlite3.js',
    'c:\\HomeAssistant\\db\\sqlite_db\\index.js',
    'c:\\HomeAssistant\\db\\index.js',
    'c:\\HomeAssistant\\server.js'
  ]
}
(node:13976) UnhandledPromiseRejectionWarning: Error: Cannot find module 'c:\HomeAssistant\node_modules\sqlite3\lib\binding\node-v72-win32-x64\node_sqlite3.node'
Require stack:
- c:\HomeAssistant\node_modules\sqlite3\lib\sqlite3.js
- c:\HomeAssistant\db\sqlite_db\index.js
- c:\HomeAssistant\db\index.js
- c:\HomeAssistant\server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:610:15)
    at Function.Module._load (internal/modules/cjs/loader.js:526:27)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (c:\HomeAssistant\node_modules\sqlite3\lib\sqlite3.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
(node:13976) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:13976) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Done in 3.54s.

**Comment by Ashish117** [comment]
Delete sqlite3 from node_modules and then c:\HomeAssistant> npm install

**Comment by likegeo** [comment]
Thank you for your reply, i tried but same problem...

**Comment by likegeo** [comment]
fixed, i have downgraded nodejs to v6.13, all is ok now.

Thank you :)

**Comment by patrickjquinn** [comment]
Closing this issue as it seems to have been resolved :)
